// Entry action types
export const ADD_ENTRY = 'ADD_ENTRY';
export const ADD_ENTRIES = 'ADD_ENTRIES';
export const REMOVE_ENTRY = 'REMOVE_ENTRY';

// Hull action types
export const ADD_HULL = 'ADD_HULL';
export const RESIZE_HULL_AXES = 'RESIZE_HULL_AXES';
export const SET_POINTS_VISIBLITY = 'SET_POINTS_VISIBLITY';
export const SET_HULL_POINTS_VISIBLITY = 'SET_HULL_POINTS_VISIBLITY';
export const POINT_CLICK_HANDLER = 'POINT_CLICK_HANDLER';
export const SET_SELECTED_HULL = 'SET_SELECTED_HULL';
export const REMOVE_HULL = 'REMOVE_HULL';
export const CLEAR_SELECTED_HULLS = 'CLEAR_SELECTED_HULLS';
// Hull Sidebar actions
export const SHOW_ALL_POINTS = 'SHOW_ALL_POINTS';
export const RESET_HULL = 'RESET_HULL';
export const TOGGLE_LABELS = 'TOGGLE_LABELS';

// Periodic table action types
export const ADD_ELEMENT = 'ADD_ELEMENT';
export const ADD_ELEMENTS = 'ADD_ELEMENTS';
export const REMOVE_ELEMENT = 'REMOVE_ELEMENT';
export const RESET = 'RESET_PTABLE';
export const UPDATE_AVAILABLE_ELEMENTS = 'UPDATE_AVAILABLE_ELEMENTS';
export const GET_AVAILABLE_ELEMENTS = 'GET_AVAILABLE_ELEMENTS';
export const GET_SELECTED_ELEMENTS = 'GET_SELECTED_ELEMENTS';
